name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: Lint Java Code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint Java Code (checkstyle)
        run: ./gradlew checkstyleMain checkstyleTest

  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ "21"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Unit Tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    name: Build Spring Boot Application
    needs:
      - test
      - check
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ "21"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Jar
        run: ./gradlew bootJar

      - uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/bswe.jar

  check:
    runs-on: ubuntu-latest
    name: Code Quality Checks
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ "21"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Checks
        run: ./gradlew check
        continue-on-error: true

  #  angular-build:
  #    runs-on: ubuntu-latest
  #    name: Build Angular Application
  #    needs: build
  #    strategy:
  #      max-parallel: 4
  #    steps:
  #      - name: Checkout repository
  #        uses: actions/checkout@v4
  #
  #      - name: Setup Node.js
  #        uses: actions/setup-node@v4
  #        with:
  #          node-version: "16"
  #
  #      - name: Install Angular Dependencies
  #       run: npm install
  #
  #     - name: Run Tests
  #       run: npm test
  #
  #     - name: Build Angular Project
  #       run: npm run build
